// src/styles.jsx
export const styles = {
    multiStepForm: {
      background: 'white',
      padding: '2rem',
      borderRadius: '10px',
      boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
      maxWidth: '500px',
      width: '100%',
      margin: '0 auto',
      justifyContent: 'center', 
    },
    formContainer: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
    },
    formGroup: {
      marginBottom: '1.5rem',
    },
    input: {
      padding: '0.75rem',
      border: '1px solid #ccc',
      borderRadius: '8px',
      width: '100%',
      fontSize: '1rem',
    },
    textarea: {
      padding: '0.75rem',
      border: '1px solid #ccc',
      borderRadius: '8px',
      width: '100%',
      minHeight: '100px',
      fontSize: '1rem',
    },
    error: {
      color: 'red',
      fontSize: '0.875rem',
      marginTop: '0.5rem',
    },
    nextButton: {
      padding: '0.75rem 1.5rem',
      border: 'none',
      borderRadius: '8px',
      backgroundColor: '#007bff',
      color: 'white',
      cursor: 'pointer',
      fontSize: '1rem',
      marginLeft: '1rem',
    },
    backButton: {
      padding: '0.75rem 1.5rem',
      border: 'none',
      borderRadius: '8px',
      backgroundColor: '#6c757d',
      color: 'white',
      cursor: 'pointer',
      fontSize: '1rem',
    },
    submitButton: {
      padding: '0.75rem 1.5rem',
      border: 'none',
      borderRadius: '8px',
      backgroundColor: '#28a745',
      color: 'white',
      cursor: 'pointer',
      fontSize: '1rem',
    },
    reviewSection: {
      background: '#f9f9f9',
      padding: '1.5rem',
      borderRadius: '8px',
      marginBottom: '1.5rem',
    },
    buttonGroup: {
      display: 'flex',
      justifyContent: 'flex-end',
      marginTop: '1.5rem',
    },
  };